Create simple UI kit module
Hopstok/rock-recepies pull request #17
Opened 2018-12-06 22:26 UTC by ptesser

Ho creato le basi per il modulo UI.

In pratica ho generato un modulo esterno al progetto principale usando la libreria UI esterna https://vmware.github.io/clarity.

Questo consente di rimpiazzare facilmente le componenti che poi andremmo ad usare perché noi di fatto usiamo il wrapper e non direttamente la libreria.

Ho solo implementato (e neanche credo completamente) l'elemento di input e combobox per vedere che l'integrazione funzionasse correttamente.

Propongo di mergiare questa cosa in maniera semplice e all'occorrenza estendere con nuovi elementi,

2018-12-07 08:32 UTC, ptesser commented
@LucaVannucci Nel mentre ho aggiunto anche Travis per provare le build e i linting su CI, però se preferisci sposto la cosa su un'altra branch.

2018-12-07 11:04 UTC, LucaVannucci commented
No va bene vai tranquillo

> Il giorno 7 dic 2018, alle ore 09:32, Paolo Tesser <notifications@github.com> ha scritto:
> 
> @LucaVannucci <https://github.com/LucaVannucci> Nel mentre ho aggiunto anche Travis per provare le build e i linting su CI, però se preferisci sposto la cosa su un'altra branch.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/Hopstok/rock-recepies/pull/17#issuecomment-445160013>, or mute the thread <https://github.com/notifications/unsubscribe-auth/Ao--xlNSvIjCEcoC2p4jxesMsssZSIBfks5u2iengaJpZM4ZHbo5>.
>

2019-02-02 17:00 UTC, Vannnu requested changes

2019-02-02 17:00 UTC, Vannnu commented on front-end/projects/ui/src/lib/input/input.component.spec.ts
> +
Line

2019-02-02 17:00 UTC, Vannnu commented on front-end/projects/ui/src/lib/select/select.component.spec.ts
> +
Line

2019-02-02 17:00 UTC, Vannnu commented on front-end/projects/ui/src/lib/select/select.component.ts
> +
Line

2019-02-02 17:00 UTC, Vannnu commented on front-end/projects/ui/src/lib/ui.component.spec.ts
> +
Line

2019-02-02 17:00 UTC, Vannnu commented on front-end/projects/ui/src/lib/ui.module.ts
> +
Line

2019-02-02 17:00 UTC, Vannnu commented on front-end/projects/ui/src/lib/ui.module.ts
> +const COMPONENTS = [
Explain the behavior of the const

2019-02-02 17:15 UTC, ptesser commented on front-end/projects/ui/src/lib/ui.module.ts
> +
La linea è usata per separare gli import esterni da quelli interni. Vale anche per le altre parti

2019-02-02 17:16 UTC, ptesser commented on front-end/projects/ui/src/lib/ui.module.ts
> +const COMPONENTS = [
In che senso? è un array di componenti che uso sia nelle dichiarazioni del modulo sia negli export, ovvero quello che il modulo espone all'esterno.

2019-02-02 17:17 UTC, ptesser commented on front-end/projects/ui/src/lib/input/input.component.spec.ts
> +
Vedi altro commento.

2019-02-02 17:17 UTC, ptesser commented on front-end/projects/ui/src/lib/input/input.component.ts
> +import { UiFormControl } from '../ui-form-control';
Qua devo separare, sistemo.

2019-02-02 17:18 UTC, ptesser commented on front-end/projects/ui/src/lib/select/select.component.spec.ts
> +
Vedi altro commento più significativo.

2019-02-02 17:18 UTC, ptesser commented on front-end/projects/ui/src/lib/select/select.component.ts
> +
Idem

2019-02-02 17:18 UTC, ptesser commented on front-end/projects/ui/src/lib/ui.component.spec.ts
> +
Idem

2019-04-29 16:37 UTC, closed without merging